Talan\Bundle\DynamicFormBundle\Entity\StringValue:
    type: entity
    table: talan_string_value
    fields:
        value:
            type: string
            length: 255
    lifecycleCallbacks: {  }
