Talan\Bundle\DynamicFormBundle\Entity\ValueOwnerType:
    type: entity
    table: talan_value_owner_type
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        
    fields:
        label:
            type: string
            length: 100
        tagName:
            type: string
            length: 100
        description:
            type: text
            nullable: true
            
    oneToMany:
        forms:
            targetEntity: Form
            mappedBy: valueOwnerType
            cascade: ["persist", "remove"]
            orphanRemoval: true
                
    lifecycleCallbacks: {  }
