Talan\Bundle\DynamicFormBundle\Entity\Value:
    type: entity
    table: talan_value
    inheritanceType: JOINED
    repositoryClass: Talan\Bundle\DynamicFormBundle\Entity\Repository\ValueRepository
    indexes:
        search_index:
            columns: [ value_owner, field_id ]
    uniqueConstraints:
        search_idx:
            columns: [ value_owner, field_id ]
    discriminatorColumn:
        name: discr
        type: string
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:    
        valueOwner:
            column: value_owner
            type: string
            length: 100
            nullable: true
                 
    manyToOne:
        field:
            targetEntity: Field
            inversedBy: values
                                
    lifecycleCallbacks: {  }