talan_dynamic_form_bo:
    path:     /bo/{form}
    defaults: { _controller: "TalanDynamicFormBundle:BO:form", form: null }
    
talan_dynamic_form_fo:
    path:     /fo/{form}   
    defaults: { _controller: "TalanDynamicFormBundle:FO:form"}
talan_dynamic_form_fields:
    path:     /fields/{form}
    defaults: { _controller: "TalanDynamicFormBundle:FO:getFields"}
talan_dynamic_form_values:
    path:     /fields/{form}
    defaults: { _controller: "TalanDynamicFormBundle:FO:getValues"}