talan_dynamic_form_bo:
    path:     /bo/{form}
    defaults: { _controller: "TalanDynamicFormBundle:BO:form", form: null }
talan_dynamic_form_bo_remove:    
    path:     /bo/remove/{form}
    defaults: { _controller: "TalanDynamicFormBundle:BO:remove" }
talan_dynamic_form_bo_ownerList:    
    path:     /owners/{form}
    defaults: { _controller: "TalanDynamicFormBundle:BO:ownerList" }
    
talan_dynamic_form_fo:
    path:     /fo/{form}   
    defaults: { _controller: "TalanDynamicFormBundle:FO:form"}    
talan_dynamic_form_fields:
    path:     /fields/{form}/{valueOwner}
    defaults: { _controller: "TalanDynamicFormBundle:FO:getFields", valueOwner: null}
