parameters:
    talan_dynamic_form.json_parse.class: Talan\Bundle\DynamicFormBundle\Service\FormJsonParser
    
services:
    talan_dynamic_form.json_parser:
        class: "%talan_dynamic_form.json_parse.class%"
        arguments: ["@doctrine.orm.entity_manager"]