language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=2.3.*
    - SYMFONY_VERSION=2.4.*
    - SYMFONY_VERSION=2.5.*

before_script:
    - composer self-update
    - composer install --dev
    
script: 
    - phpunit --coverage-text
    - phpunit --coverage-clover build/logs/clover.xml    

notifications:
  email: aymen.bouchakoua@talan.tn